version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    networks:
      - primary
    volumes:
      - ./backend:/rails
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./general-data/db:/var/lib/postgresql/data
    networks:
      - primary
    environment:
      - POSTGRES_DB=devise
      - POSTGRES_USER=devise
      - POSTGRES_PASSWORD=devise
    ports:
      - "5432:5432"

networks:
  primary:
    driver: bridge