services:
  db:
    image: postgres
    volumes:
      - ./general-data/db:/var/lib/postgresql/data
    networks:
      - primary
    environment:
      - POSTGRES_DB=devise
      - POSTGRES_USER=devise
      - POSTGRES_PASSWORD=devise
    ports:
      - "5432:5432"

  backend:
    build: backend
    # image: rails-backend
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3001:3000"
    networks:
      - primary
    working_dir: /backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  frontend:
    build: frontend
    # image: react-frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - primary
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend

networks:
  primary:
    driver: bridge